### ISSUE TITLE
New gram! Wow!

### ISSUE THREAD

**Issue by qwq233** [PreviousAlone/Nnngram#1]
这都第几个了

**Comment by NextAlone** [comment]
为什么不好好上学, 看什么GitHub

**Comment by qwq233** [comment]
草 改title可还行

**Comment by qwq233** [comment]
噗 合着你这fork我的啊

**Comment by NextAlone** [comment]
> 噗 合着你这fork我的啊

从官方改太多了，直接改你的比较快

**Comment by qwq233** [comment]
行 别改我code header和其他版权声明啥的其他无所谓

**Comment by NextAlone** [comment]
a capoo yes

**Comment by TontyTon** [comment]
I don't think it need a new 'issue', if you want I can open a new issue too.

@NextAlone

Just want to ask, what is/are the difference(s) between Nullgram and nnngram?
Or you just compile nullgram and release?
