### ISSUE TITLE
[feature] 将删除消息的默认行为改为同时为对方删除

### ISSUE THREAD

**Issue by UptonEdward** [PreviousAlone/Nnngram#17]
### Why do you think you need this feature

在私聊中删除消息时，当前的默认行为是仅为自己删除，想要为双方删除需要再点击「同时为 xxx 删除」，如果忘记点击，那么该消息会在本人所有设备上全部消失，就再也不能为对方删除了。这其实类似于把微信的 _撤回_ 变成 _删除_ ，对于用户的隐私保护实属不利。如果能讲默认行为改变成「同时为 xx 删除」，那么即使误删了消息也可以重新发送，不至于出现上面的窘境。

### Describe the solution you'd like

我认为 Nagram 的实现方法就很好。

**Comment by NextAlone** [comment]
@UptonEdward 好

**Comment by NextAlone** [comment]
Done in a7776d6a5ea428a312914d670ea33b015c3ace83
