### ISSUE TITLE
Sorry oot I'm using Nagram akun banned From telegram [Bug] 

### ISSUE THREAD

**Issue by mozzaru** [PreviousAlone/Nnngram#21]
### Steps to reproduce

sorry oo I use the latest version of Nagram and use it before logging in safely. Suddenly, for more than 1 month, my telegram account has been banned 3 times.

### Expected behaviour

sorry oo I use the latest version of Nagram and use it before logging in safely. Suddenly, for more than 1 month, my telegram account has been banned 3 times.

### Actual behaviour

sorry oo I use the latest version of Nagram and use it before logging in safely. Suddenly, for more than 1 month, my telegram account has been banned 3 times.

### Smartphone Information

Android 11

### Nnngram Version

Last

### Version requirement

- [X] I am using latest debug CI version of Nnngram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

sorry oo I use the latest version of Nagram and use it before logging in safely. Suddenly, for more than 1 month, my telegram account has been banned 3 times.

**Comment by NextAlone** [comment]
If you encounter these problems, it is recommended to use the official solution instead of relying on third-party Telegram developers who may not be familiar with the issue at hand. This is not the fault of Nnngram/Nagram itself.

**Comment by Zhongli0401** [comment]
> If you encounter these problems, it is recommended to use the official solution instead of relying on third-party Telegram developers who may not be familiar with the issue at hand. This is not the fault of Nnngram and Nagram themselves.

i think he is just bsing also if he did something in dev settings it can give u ban
