### ISSUE TITLE
[feature] 希望消息过滤器支持输入多个关键词

### ISSUE THREAD

**Issue by ypq123456789** [PreviousAlone/Nnngram#46]
### Why do you think you need this feature

现在消息过滤器是用的正则表达式，需要用 aaa|bbb|ccc 的形式输入，感觉不是特别方便

### Describe the solution you'd like

希望大佬能支持一行输入一个关键词，不断新增这样。最好的情况是直接长按某条消息就可以新增过滤整条消息或者其中某个关键词

**Comment by NextAlone** [comment]
@ypq123456789 现在就可以长按消息选择关键词过滤

**Comment by ypq123456789** [comment]
> @ypq123456789 现在就可以长按消息选择关键词过滤

原来是支持的 没事了 谢谢大佬
