### ISSUE TITLE
｛bug｝在表情面板经常卡死

### ISSUE THREAD

**Issue by Keeperorowner** [PreviousAlone/Nnngram#47]
### Steps to reproduce

![Screenshot_2024-07-29-14-57-13-55_f2c90dfdeeada6d707963a73d5081779](https://github.com/user-attachments/assets/09c73f21-ebba-47a4-bc12-7e585a7e9444)
在这个界面，大概率卡死

### Expected behaviour

不卡死

### Actual behaviour

卡死

### Smartphone Information

一加 Ace 3

### Nnngram Version

v10.14.5-ddf84e0(1720963081)

### Version requirement

- [X] I am using latest debug CI version of Nnngram and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs

[log-2024-07-29.txt](https://github.com/user-attachments/files/16408688/log-2024-07-29.txt)

**Comment by NextAlone** [comment]
@Keeperorowner 来 tg 反馈，github 有时候会忽略掉

**Comment by NextAlone** [comment]
@Keeperorowner 来点 log

**Comment by NextAlone** [comment]
@Keeperorowner 屏蔽赞助信息打开了吗？

**Comment by NextAlone** [comment]
@Keeperorowner 嗯嗯先关掉吧 我后面看看为啥

**Comment by NextAlone** [comment]
@Keeperorowner log 跟之前一样吗

**Comment by NextAlone** [comment]
@Keeperorowner 搜搜 FATAL Exception

**Comment by NextAlone** [comment]
> 发现应该是tmoe模块的问题

好哦

**Comment by Chen-hai-0721** [comment]
@NextAlone 我刚才也遇到这个问题了，只要查看表情面板时间稍微长一点，就会卡死，不是百分百触发的，把应用强制停止之后在重启就。又不会卡死了
